version: "3.7"

networks:
  myNetwork:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    networks:
      - myNetwork
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    networks:
      - myNetwork
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,RMOFF_DOCKER_HACK://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.5:9092,RMOFF_DOCKER_HACK://host.docker.internal:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,RMOFF_DOCKER_HACK:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
