version: "3.7"

networks: # tạo mạng để các dịch vụ có thể giao tiếp được với nhau
  myNetwork:
    driver: bridge

services:
  zookeeper: # hỗ trợ cho kafka server, là nơi lưu dữ liệu phân tán, quản lý các kafka broker
    image: "bitnami/zookeeper:latest"
    networks:
      - myNetwork
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka: # kafka server
    image: "bitnami/kafka:latest"
    networks:
      - myNetwork
    ports:
      - "9093:9093" # cổng kết nối giao tiếp ra bên ngoài(giao tiếp bên trong qua cổng 9092)
    environment: # biến môi trường chứa các thông số cấu hình cho việc kết nối
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  producer-kafka: # bên cung cấp tin nhắn
    build: # sử dụng dockerfile để build
      context: .
      dockerfile: Dockerfile-producer
    networks:
      - myNetwork
    environment:
      - OMP_NUM_THREADS=4 # số thread chạy trên ứng dụng
      - PRESSURE_TOPIC=pressure # topic áp suất
      - TEMPERATURE_TOPIC=temperature # topic nhiệt độ
      - BOOTSTRAP_SERVER=kafka:9092 # kết nối đến kafka server
      - SASL_MECHANISM=SCRAM-SHA-256
      - SASL_USERNAME=user_test1
      - SASL_PASSWORD=12345678
      - SSL_KEYSTORE_LOCATION=D:\\kafka\\kafka.keystore.jks
      - SSL_KEYSTORE_PASSWORD=FzOGrwIE
      - SSL_KEY_LOCATION=D:\\kafka\\kafka.truststore.jks
      - SSL_KEY_PASSWORD=FzOGrwIE
    depends_on:
      - zookeeper
      - kafka

  consumer-kafka: # bên đăng ký và nhận các tin nhắn
    build:
      context: .
      dockerfile: Dockerfile-consumer
    networks:
      - myNetwork
    environment:
      - PRESSURE_TOPIC=pressure
      - TEMPERATURE_TOPIC=temperature
      - BOOTSTRAP_SERVER=kafka:9092
      - SASL_MECHANISM=SCRAM-SHA-256
      - SASL_USERNAME=user_test1
      - SASL_PASSWORD=12345678
      - SSL_KEYSTORE_LOCATION=D:\\kafka\\kafka.keystore.jks
      - SSL_KEYSTORE_PASSWORD=FzOGrwIE
      - SSL_KEY_LOCATION=D:\\kafka\\kafka.truststore.jks
      - SSL_KEY_PASSWORD=FzOGrwIE
      - GROUP_ID=id1
    depends_on:
      - zookeeper
      - kafka
